# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_compression.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1634, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/extendedbothways.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(20, 2))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 28))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 28))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnInput = QtWidgets.QToolButton(self.frame)
        self.btnInput.setGeometry(QtCore.QRect(0, 0, 28, 28))
        self.btnInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInput.setIcon(icon1)
        self.btnInput.setIconSize(QtCore.QSize(18, 18))
        self.btnInput.setObjectName("btnInput")
        self.btnOutput = QtWidgets.QToolButton(self.frame)
        self.btnOutput.setGeometry(QtCore.QRect(30, 0, 28, 28))
        self.btnOutput.setFocusPolicy(QtCore.Qt.TabFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/output.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOutput.setIcon(icon2)
        self.btnOutput.setIconSize(QtCore.QSize(18, 18))
        self.btnOutput.setObjectName("btnOutput")
        self.btnTop = QtWidgets.QToolButton(self.frame)
        self.btnTop.setGeometry(QtCore.QRect(160, 0, 28, 28))
        self.btnTop.setFocusPolicy(QtCore.Qt.TabFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/X-Y.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTop.setIcon(icon3)
        self.btnTop.setIconSize(QtCore.QSize(22, 22))
        self.btnTop.setObjectName("btnTop")
        self.btnFront = QtWidgets.QToolButton(self.frame)
        self.btnFront.setGeometry(QtCore.QRect(100, 0, 28, 28))
        self.btnFront.setFocusPolicy(QtCore.Qt.TabFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/Z-X.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFront.setIcon(icon4)
        self.btnFront.setIconSize(QtCore.QSize(22, 22))
        self.btnFront.setObjectName("btnFront")
        self.btnSide = QtWidgets.QToolButton(self.frame)
        self.btnSide.setGeometry(QtCore.QRect(130, 0, 28, 28))
        self.btnSide.setFocusPolicy(QtCore.Qt.TabFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/Z-Y.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSide.setIcon(icon5)
        self.btnSide.setIconSize(QtCore.QSize(22, 22))
        self.btnSide.setObjectName("btnSide")
        self.btn3D = QtWidgets.QCheckBox(self.frame)
        self.btn3D.setGeometry(QtCore.QRect(220, 0, 90, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn3D.setFont(font)
        self.btn3D.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn3D.setObjectName("btn3D")
        self.chkBx_beamSec = QtWidgets.QCheckBox(self.frame)
        self.chkBx_beamSec.setGeometry(QtCore.QRect(410, 0, 71, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chkBx_beamSec.setFont(font)
        self.chkBx_beamSec.setFocusPolicy(QtCore.Qt.TabFocus)
        self.chkBx_beamSec.setObjectName("chkBx_beamSec")
        self.chkBx_connector = QtWidgets.QCheckBox(self.frame)
        self.chkBx_connector.setGeometry(QtCore.QRect(490, 0, 151, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chkBx_connector.setFont(font)
        self.chkBx_connector.setFocusPolicy(QtCore.Qt.TabFocus)
        self.chkBx_connector.setObjectName("chkBx_connector")
        self.chkBx_columnSec = QtWidgets.QCheckBox(self.frame)
        self.chkBx_columnSec.setGeometry(QtCore.QRect(310, 0, 91, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chkBx_columnSec.setFont(font)
        self.chkBx_columnSec.setFocusPolicy(QtCore.Qt.TabFocus)
        self.chkBx_columnSec.setObjectName("chkBx_columnSec")
        self.verticalLayout_2.addWidget(self.frame)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mytabWidget = QtWidgets.QTabWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mytabWidget.sizePolicy().hasHeightForWidth())
        self.mytabWidget.setSizePolicy(sizePolicy)
        self.mytabWidget.setMinimumSize(QtCore.QSize(0, 450))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.mytabWidget.setFont(font)
        self.mytabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mytabWidget.setStyleSheet("QTabBar::tab { height: 75px; width: 1px;  }")
        self.mytabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.mytabWidget.setObjectName("mytabWidget")
        self.verticalLayout.addWidget(self.mytabWidget)
        self.textEdit = QtWidgets.QTextEdit(self.splitter)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 125))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setReadOnly(True)
        self.textEdit.setOverwriteMode(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1634, 26))
        self.menubar.setStyleSheet("")
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("QMenu {\n"
"    background-color:#b2bd84;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"    margin: 2px; /* some spacing around the menu */\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    color: black;\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"   color:white;\n"
"    border-color: darkblue;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"")
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setStyleSheet("QMenu {\n"
"    background-color:#b2bd84;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"    margin: 2px; /* some spacing around the menu */\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    color: black;\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"   color:white;\n"
"    border-color: darkblue;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"")
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setStyleSheet("QMenu {\n"
"    background-color:#b2bd84;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"    margin: 2px; /* some spacing around the menu */\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    color: black;\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"   color:white;\n"
"    border-color: darkblue;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"")
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("QMenu {\n"
"    background-color:#b2bd84;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"    margin: 2px; /* some spacing around the menu */\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    color: black;\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"   color:white;\n"
"    border-color: darkblue;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"")
        self.menuHelp.setObjectName("menuHelp")
        self.menuGraphics = QtWidgets.QMenu(self.menubar)
        self.menuGraphics.setStyleSheet("QMenu {\n"
"    background-color:#b2bd84;\n"
"    border-color: black;\n"
"    border: 1px solid;\n"
"    margin: 2px; /* some spacing around the menu */\n"
"}\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    color: black;\n"
"    padding: 2px 20px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"   color:white;\n"
"    border-color: darkblue;\n"
"    background: #825051;\n"
"    margin-left: 5px;\n"
"    margin-right: 5px;\n"
"}")
        self.menuGraphics.setObjectName("menuGraphics")
        MainWindow.setMenuBar(self.menubar)
        self.outputDock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDock.sizePolicy().hasHeightForWidth())
        self.outputDock.setSizePolicy(sizePolicy)
        self.outputDock.setMinimumSize(QtCore.QSize(125, 710))
        self.outputDock.setMaximumSize(QtCore.QSize(366, 710))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.outputDock.setFont(font)
        self.outputDock.setObjectName("outputDock")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.label_157 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_157.setGeometry(QtCore.QRect(0, 5, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_157.setFont(font)
        self.label_157.setObjectName("label_157")
        self.btn_SaveMessages = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btn_SaveMessages.setGeometry(QtCore.QRect(50, 614, 200, 30))
        self.btn_SaveMessages.setAutoDefault(True)
        self.btn_SaveMessages.setObjectName("btn_SaveMessages")
        self.btn_CreateDesign = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btn_CreateDesign.setGeometry(QtCore.QRect(50, 650, 200, 30))
        self.btn_CreateDesign.setAutoDefault(True)
        self.btn_CreateDesign.setObjectName("btn_CreateDesign")
        self.txt_slender_yy = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.txt_slender_yy.setGeometry(QtCore.QRect(220, 260, 100, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_slender_yy.setFont(font)
        self.txt_slender_yy.setReadOnly(True)
        self.txt_slender_yy.setObjectName("txt_slender_yy")
        self.txt_comp_capacity_zz = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.txt_comp_capacity_zz.setGeometry(QtCore.QRect(220, 60, 100, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_comp_capacity_zz.setFont(font)
        self.txt_comp_capacity_zz.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txt_comp_capacity_zz.setText("")
        self.txt_comp_capacity_zz.setReadOnly(True)
        self.txt_comp_capacity_zz.setObjectName("txt_comp_capacity_zz")
        self.txt_comp_capacity_yy = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.txt_comp_capacity_yy.setGeometry(QtCore.QRect(220, 130, 100, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_comp_capacity_yy.setFont(font)
        self.txt_comp_capacity_yy.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txt_comp_capacity_yy.setReadOnly(True)
        self.txt_comp_capacity_yy.setObjectName("txt_comp_capacity_yy")
        self.label_156 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_156.setGeometry(QtCore.QRect(0, 30, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_156.setFont(font)
        self.label_156.setObjectName("label_156")
        self.label_159 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_159.setGeometry(QtCore.QRect(0, 110, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_159.setFont(font)
        self.label_159.setObjectName("label_159")
        self.label_170 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_170.setGeometry(QtCore.QRect(0, 310, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.label_171 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_171.setGeometry(QtCore.QRect(0, 200, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_171.setFont(font)
        self.label_171.setObjectName("label_171")
        self.txt_slender_zz = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.txt_slender_zz.setGeometry(QtCore.QRect(220, 200, 100, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_slender_zz.setFont(font)
        self.txt_slender_zz.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txt_slender_zz.setReadOnly(True)
        self.txt_slender_zz.setObjectName("txt_slender_zz")
        self.label_172 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_172.setGeometry(QtCore.QRect(0, 260, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_172.setFont(font)
        self.label_172.setObjectName("label_172")
        self.label_173 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_173.setGeometry(QtCore.QRect(0, 370, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_173.setFont(font)
        self.label_173.setObjectName("label_173")
        self.txt_efficiency_zz = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.txt_efficiency_zz.setGeometry(QtCore.QRect(220, 310, 100, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_efficiency_zz.setFont(font)
        self.txt_efficiency_zz.setReadOnly(True)
        self.txt_efficiency_zz.setObjectName("txt_efficiency_zz")
        self.txt_efficiency_yy = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.txt_efficiency_yy.setGeometry(QtCore.QRect(220, 370, 100, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txt_efficiency_yy.setFont(font)
        self.txt_efficiency_yy.setReadOnly(True)
        self.txt_efficiency_yy.setObjectName("txt_efficiency_yy")
        self.outputDock.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.outputDock)
        self.inputDock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDock.sizePolicy().hasHeightForWidth())
        self.inputDock.setSizePolicy(sizePolicy)
        self.inputDock.setMinimumSize(QtCore.QSize(310, 710))
        self.inputDock.setMaximumSize(QtCore.QSize(310, 750))
        self.inputDock.setBaseSize(QtCore.QSize(310, 710))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.inputDock.setFont(font)
        self.inputDock.setFloating(False)
        self.inputDock.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.inputDock.setObjectName("inputDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.txt_Fy = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txt_Fy.setGeometry(QtCore.QRect(150, 220, 160, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Fy.setFont(font)
        self.txt_Fy.setObjectName("txt_Fy")
        self.txt_Fu = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txt_Fu.setGeometry(QtCore.QRect(150, 170, 160, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Fu.setFont(font)
        self.txt_Fu.setObjectName("txt_Fu")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl_fu = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_fu.setGeometry(QtCore.QRect(10, 170, 120, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_fu.setFont(font)
        self.lbl_fu.setObjectName("lbl_fu")
        self.lbl_fy = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_fy.setGeometry(QtCore.QRect(10, 220, 120, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_fy.setFont(font)
        self.lbl_fy.setObjectName("lbl_fy")
        self.btn_Reset = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_Reset.setGeometry(QtCore.QRect(30, 660, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Reset.setFont(font)
        self.btn_Reset.setAutoDefault(True)
        self.btn_Reset.setObjectName("btn_Reset")
        self.btn_Design = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_Design.setGeometry(QtCore.QRect(160, 660, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Design.setFont(font)
        self.btn_Design.setAutoDefault(True)
        self.btn_Design.setObjectName("btn_Design")
        self.lbl_column = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_column.setGeometry(QtCore.QRect(10, 70, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_column.setFont(font)
        self.lbl_column.setObjectName("lbl_column")
        self.combo_sectiontype = QtWidgets.QComboBox(self.dockWidgetContents)
        self.combo_sectiontype.setGeometry(QtCore.QRect(150, 70, 160, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.combo_sectiontype.setFont(font)
        self.combo_sectiontype.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.combo_sectiontype.setMaxVisibleItems(5)
        self.combo_sectiontype.setObjectName("")
        self.combo_sectiontype.addItem("")
        self.combo_sectiontype.addItem("")
        self.combo_sectiontype.addItem("")
        self.combo_sectiontype.addItem("")
        self.combo_sectiontype.addItem("")
        self.combo_sectiontype.addItem("")
        self.combo_sectiontype.addItem("")
        self.combo_sectiontype.addItem("")
        self.label_18 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(10, 400, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.txt_Compressionforce = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txt_Compressionforce.setGeometry(QtCore.QRect(150, 440, 160, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Compressionforce.setFont(font)
        self.txt_Compressionforce.setObjectName("txt_Compressionforce")
        self.lbl_axial = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_axial.setGeometry(QtCore.QRect(10, 440, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_axial.setFont(font)
        self.lbl_axial.setObjectName("lbl_axial")
        self.txt_Member_length_zz = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txt_Member_length_zz.setGeometry(QtCore.QRect(150, 270, 160, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Member_length_zz.setFont(font)
        self.txt_Member_length_zz.setObjectName("txt_Member_length_zz")
        self.lbl_beam1_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_beam1_10.setGeometry(QtCore.QRect(10, 270, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_beam1_10.setFont(font)
        self.lbl_beam1_10.setObjectName("lbl_beam1_10")
        self.combo_end1_cond1 = QtWidgets.QComboBox(self.dockWidgetContents)
        self.combo_end1_cond1.setGeometry(QtCore.QRect(150, 520, 160, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.combo_end1_cond1.setFont(font)
        self.combo_end1_cond1.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.combo_end1_cond1.setMaxVisibleItems(5)
        self.combo_end1_cond1.setObjectName("combo_end1_cond1")
        self.combo_end1_cond1.addItem("")
        self.combo_end1_cond1.addItem("")
        self.combo_end1_cond1.addItem("")
        self.combo_end2_cond1 = QtWidgets.QComboBox(self.dockWidgetContents)
        self.combo_end2_cond1.setGeometry(QtCore.QRect(150, 580, 160, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.combo_end2_cond1.setFont(font)
        self.combo_end2_cond1.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.combo_end2_cond1.setMaxVisibleItems(5)
        self.combo_end2_cond1.setObjectName("combo_end2_cond1")
        self.combo_end2_cond1.addItem("")
        self.combo_end2_cond1.addItem("")
        self.combo_end2_cond1.addItem("")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(10, 530, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.combo_end2_cond2 = QtWidgets.QComboBox(self.dockWidgetContents)
        self.combo_end2_cond2.setGeometry(QtCore.QRect(150, 610, 160, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.combo_end2_cond2.setFont(font)
        self.combo_end2_cond2.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.combo_end2_cond2.setMaxVisibleItems(5)
        self.combo_end2_cond2.setObjectName("combo_end2_cond2")
        self.combo_end2_cond2.addItem("")
        self.combo_end2_cond2.addItem("")
        self.combo_end2_cond2.addItem("")
        self.combo_end1_cond2 = QtWidgets.QComboBox(self.dockWidgetContents)
        self.combo_end1_cond2.setGeometry(QtCore.QRect(150, 550, 160, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.combo_end1_cond2.setFont(font)
        self.combo_end1_cond2.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.combo_end1_cond2.setMaxVisibleItems(5)
        self.combo_end1_cond2.setObjectName("combo_end1_cond2")
        self.combo_end1_cond2.addItem("")
        self.combo_end1_cond2.addItem("")
        self.combo_end1_cond2.addItem("")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(10, 590, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_43 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_43.setGeometry(QtCore.QRect(10, 490, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lbl_column_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_column_2.setGeometry(QtCore.QRect(10, 120, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_column_2.setFont(font)
        self.lbl_column_2.setObjectName("lbl_column_2")
        self.combo_sectionsize = QtWidgets.QComboBox(self.dockWidgetContents)
        self.combo_sectionsize.setGeometry(QtCore.QRect(150, 120, 160, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.combo_sectionsize.setFont(font)
        self.combo_sectionsize.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.combo_sectionsize.setMaxVisibleItems(5)
        self.combo_sectionsize.setObjectName("combo_sectionsize")
        self.txt_plate_thk = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txt_plate_thk.setGeometry(QtCore.QRect(150, 360, 160, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plate_thk.setFont(font)
        self.txt_plate_thk.setObjectName("txt_plate_thk")
        self.Plate_thk = QtWidgets.QLabel(self.dockWidgetContents)
        self.Plate_thk.setGeometry(QtCore.QRect(10, 360, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Plate_thk.setFont(font)
        self.Plate_thk.setObjectName("Plate_thk")
        self.lbl_beam1_11 = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_beam1_11.setGeometry(QtCore.QRect(10, 310, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_beam1_11.setFont(font)
        self.lbl_beam1_11.setObjectName("lbl_beam1_11")
        self.txt_Member_length_yy = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txt_Member_length_yy.setGeometry(QtCore.QRect(150, 310, 160, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Member_length_yy.setFont(font)
        self.txt_Member_length_yy.setObjectName("txt_Member_length_yy")
        self.txt_Fy.raise_()
        self.txt_Fu.raise_()
        self.label.raise_()
        self.lbl_fu.raise_()
        self.lbl_fy.raise_()
        self.btn_Reset.raise_()
        self.btn_Design.raise_()
        self.lbl_column.raise_()
        self.combo_sectiontype.raise_()
        self.label_18.raise_()
        self.txt_Compressionforce.raise_()
        self.lbl_axial.raise_()
        self.txt_Member_length_zz.raise_()
        self.lbl_beam1_10.raise_()
        self.combo_end1_cond1.raise_()
        self.combo_end2_cond1.raise_()
        self.label_8.raise_()
        self.combo_end2_cond2.raise_()
        self.combo_end1_cond2.raise_()
        self.label_10.raise_()
        self.label_43.raise_()
        self.lbl_column_2.raise_()
        self.txt_plate_thk.raise_()
        self.Plate_thk.raise_()
        self.lbl_beam1_11.raise_()
        self.txt_Member_length_yy.raise_()
        self.combo_sectionsize.raise_()
        self.inputDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.inputDock)
        self.actionInput = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInput.setIcon(icon6)
        self.actionInput.setObjectName("actionInput")
        self.actionInputwindow = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/inputview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInputwindow.setIcon(icon7)
        self.actionInputwindow.setObjectName("actionInputwindow")
        self.actionNew = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.actionNew.setFont(font)
        self.actionNew.setObjectName("actionNew")
        self.action_load_input = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setItalic(False)
        self.action_load_input.setFont(font)
        self.action_load_input.setObjectName("action_load_input")
        self.action_save_input = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.action_save_input.setFont(font)
        self.action_save_input.setObjectName("action_save_input")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClear = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionClear.setFont(font)
        self.actionClear.setObjectName("actionClear")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionCopy.setFont(font)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionPaste.setFont(font)
        self.actionPaste.setObjectName("actionPaste")
        self.actionInput_Browser = QtWidgets.QAction(MainWindow)
        self.actionInput_Browser.setObjectName("actionInput_Browser")
        self.actionOutput_Browser = QtWidgets.QAction(MainWindow)
        self.actionOutput_Browser.setObjectName("actionOutput_Browser")
        self.actionAbout_Osdag = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionAbout_Osdag.setFont(font)
        self.actionAbout_Osdag.setObjectName("actionAbout_Osdag")
        self.actionBeam = QtWidgets.QAction(MainWindow)
        self.actionBeam.setObjectName("actionBeam")
        self.actionColumn = QtWidgets.QAction(MainWindow)
        self.actionColumn.setObjectName("actionColumn")
        self.actionFinplate = QtWidgets.QAction(MainWindow)
        self.actionFinplate.setObjectName("actionFinplate")
        self.actionBolt = QtWidgets.QAction(MainWindow)
        self.actionBolt.setObjectName("actionBolt")
        self.action2D_view = QtWidgets.QAction(MainWindow)
        self.action2D_view.setObjectName("action2D_view")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionZoom_in.setFont(font)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionZoom_out.setFont(font)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionPan = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionPan.setFont(font)
        self.actionPan.setObjectName("actionPan")
        self.actionRotate_3D_model = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionRotate_3D_model.setFont(font)
        self.actionRotate_3D_model.setObjectName("actionRotate_3D_model")
        self.actionView_2D_on_XY = QtWidgets.QAction(MainWindow)
        self.actionView_2D_on_XY.setObjectName("actionView_2D_on_XY")
        self.actionView_2D_on_YZ = QtWidgets.QAction(MainWindow)
        self.actionView_2D_on_YZ.setObjectName("actionView_2D_on_YZ")
        self.actionView_2D_on_ZX = QtWidgets.QAction(MainWindow)
        self.actionView_2D_on_ZX.setObjectName("actionView_2D_on_ZX")
        self.actionModel = QtWidgets.QAction(MainWindow)
        self.actionModel.setObjectName("actionModel")
        self.actionEnlarge_font_size = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionEnlarge_font_size.setFont(font)
        self.actionEnlarge_font_size.setObjectName("actionEnlarge_font_size")
        self.actionReduce_font_size = QtWidgets.QAction(MainWindow)
        self.actionReduce_font_size.setObjectName("actionReduce_font_size")
        self.actionSave_3D_model = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionSave_3D_model.setFont(font)
        self.actionSave_3D_model.setObjectName("actionSave_3D_model")
        self.actionSave_current_image = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionSave_current_image.setFont(font)
        self.actionSave_current_image.setObjectName("actionSave_current_image")
        self.actionSave_log_messages = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionSave_log_messages.setFont(font)
        self.actionSave_log_messages.setObjectName("actionSave_log_messages")
        self.actionCreate_design_report = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionCreate_design_report.setFont(font)
        self.actionCreate_design_report.setObjectName("actionCreate_design_report")
        self.actionQuit_fin_plate_design = QtWidgets.QAction(MainWindow)
        self.actionQuit_fin_plate_design.setObjectName("actionQuit_fin_plate_design")
        self.actionSave_Front_View = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionSave_Front_View.setFont(font)
        self.actionSave_Front_View.setObjectName("actionSave_Front_View")
        self.actionSave_Top_View = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionSave_Top_View.setFont(font)
        self.actionSave_Top_View.setObjectName("actionSave_Top_View")
        self.actionSave_Side_View = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionSave_Side_View.setFont(font)
        self.actionSave_Side_View.setObjectName("actionSave_Side_View")
        self.actionChange_bg_color = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.actionChange_bg_color.setFont(font)
        self.actionChange_bg_color.setObjectName("actionChange_bg_color")
        self.actionShow_beam = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setItalic(False)
        self.actionShow_beam.setFont(font)
        self.actionShow_beam.setObjectName("actionShow_beam")
        self.actionShow_column = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionShow_column.setFont(font)
        self.actionShow_column.setObjectName("actionShow_column")
        self.actionShow_connector = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionShow_connector.setFont(font)
        self.actionShow_connector.setObjectName("actionShow_connector")
        self.actionChange_background = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        self.actionChange_background.setFont(font)
        self.actionChange_background.setObjectName("actionChange_background")
        self.actionShow_all = QtWidgets.QAction(MainWindow)
        self.actionShow_all.setObjectName("actionShow_all")
        self.actionDesign_examples = QtWidgets.QAction(MainWindow)
        self.actionDesign_examples.setObjectName("actionDesign_examples")
        self.actionSample_Problems = QtWidgets.QAction(MainWindow)
        self.actionSample_Problems.setObjectName("actionSample_Problems")
        self.actionSample_Tutorials = QtWidgets.QAction(MainWindow)
        self.actionSample_Tutorials.setObjectName("actionSample_Tutorials")
        self.actionAbout_Osdag_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_Osdag_2.setObjectName("actionAbout_Osdag_2")
        self.actionOsdag_Manual = QtWidgets.QAction(MainWindow)
        self.actionOsdag_Manual.setObjectName("actionOsdag_Manual")
        self.actionAsk_Us_a_Question = QtWidgets.QAction(MainWindow)
        self.actionAsk_Us_a_Question.setObjectName("actionAsk_Us_a_Question")
        self.actionFAQ = QtWidgets.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.actionDesign_Preferences = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        self.actionDesign_Preferences.setFont(font)
        self.actionDesign_Preferences.setShortcutVisibleInContextMenu(True)
        self.actionDesign_Preferences.setObjectName("actionDesign_Preferences")
        self.actionfinPlate_quit = QtWidgets.QAction(MainWindow)
        self.actionfinPlate_quit.setObjectName("actionfinPlate_quit")
        self.actio_load_input = QtWidgets.QAction(MainWindow)
        self.actio_load_input.setObjectName("actio_load_input")
        self.actionShow_column_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setItalic(False)

        self.combo_sectiontype.currentIndexChanged.connect(self.comboChanged)

        self.actionShow_column_2.setFont(font)
        self.actionShow_column_2.setObjectName("actionShow_column_2")
        self.menuFile.addAction(self.action_load_input)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_save_input)
        self.menuFile.addAction(self.actionSave_log_messages)
        self.menuFile.addAction(self.actionCreate_design_report)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_3D_model)
        self.menuFile.addAction(self.actionSave_current_image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Front_View)
        self.menuFile.addAction(self.actionSave_Top_View)
        self.menuFile.addAction(self.actionSave_Side_View)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionfinPlate_quit)
        self.menuEdit.addAction(self.actionClear)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDesign_Preferences)
        self.menuView.addAction(self.actionEnlarge_font_size)
        self.menuView.addSeparator()
        self.menuHelp.addAction(self.actionSample_Tutorials)
        self.menuHelp.addAction(self.actionDesign_examples)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAsk_Us_a_Question)
        self.menuHelp.addAction(self.actionAbout_Osdag_2)
        self.menuGraphics.addSeparator()
        self.menuGraphics.addAction(self.actionZoom_in)
        self.menuGraphics.addAction(self.actionZoom_out)
        self.menuGraphics.addAction(self.actionPan)
        self.menuGraphics.addAction(self.actionRotate_3D_model)
        self.menuGraphics.addSeparator()
        self.menuGraphics.addAction(self.actionShow_column_2)
        self.menuGraphics.addAction(self.actionShow_beam)
        self.menuGraphics.addAction(self.actionShow_connector)
        self.menuGraphics.addAction(self.actionShow_all)
        self.menuGraphics.addSeparator()
        self.menuGraphics.addAction(self.actionChange_background)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuGraphics.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.mytabWidget.setCurrentIndex(-1)
        self.combo_sectiontype.setCurrentIndex(0)
        self.combo_sectionsize.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.combo_sectiontype, self.combo_sectionsize)
        MainWindow.setTabOrder(self.combo_sectionsize, self.txt_Fu)
        MainWindow.setTabOrder(self.txt_Fu, self.txt_Fy)
        MainWindow.setTabOrder(self.txt_Fy, self.txt_Member_length_zz)
        MainWindow.setTabOrder(self.txt_Member_length_zz, self.txt_Member_length_yy)
        MainWindow.setTabOrder(self.txt_Member_length_yy, self.txt_plate_thk)
        MainWindow.setTabOrder(self.txt_plate_thk, self.txt_Compressionforce)
        MainWindow.setTabOrder(self.txt_Compressionforce, self.combo_end1_cond1)
        MainWindow.setTabOrder(self.combo_end1_cond1, self.combo_end1_cond2)
        MainWindow.setTabOrder(self.combo_end1_cond2, self.combo_end2_cond1)
        MainWindow.setTabOrder(self.combo_end2_cond1, self.combo_end2_cond2)
        MainWindow.setTabOrder(self.combo_end2_cond2, self.btn_Design)
        MainWindow.setTabOrder(self.btn_Design, self.btn_Reset)
        MainWindow.setTabOrder(self.btn_Reset, self.txt_slender_yy)
        MainWindow.setTabOrder(self.txt_slender_yy, self.btn_SaveMessages)
        MainWindow.setTabOrder(self.btn_SaveMessages, self.btn_CreateDesign)
        MainWindow.setTabOrder(self.btn_CreateDesign, self.textEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Osdag Compression Member Design"))
        self.btnInput.setToolTip(_translate("MainWindow", "Left Dock"))
        self.btnInput.setText(_translate("MainWindow", "input"))
        self.btnOutput.setToolTip(_translate("MainWindow", "Right Dock"))
        self.btnOutput.setText(_translate("MainWindow", "..."))
        self.btnTop.setToolTip(_translate("MainWindow", "Top View"))
        self.btnTop.setText(_translate("MainWindow", "..."))
        self.btnFront.setToolTip(_translate("MainWindow", "Front View"))
        self.btnFront.setText(_translate("MainWindow", "..."))
        self.btnSide.setToolTip(_translate("MainWindow", "Side View"))
        self.btnSide.setText(_translate("MainWindow", "..."))
        self.btn3D.setToolTip(_translate("MainWindow", "3D Model"))
        self.btn3D.setText(_translate("MainWindow", "Model"))
        self.chkBx_beamSec.setToolTip(_translate("MainWindow", "Beam only"))
        self.chkBx_beamSec.setText(_translate("MainWindow", "Beam"))
        self.chkBx_connector.setToolTip(_translate("MainWindow", "Extendedplate only"))
        self.chkBx_connector.setText(_translate("MainWindow", "Connector"))
        self.chkBx_columnSec.setToolTip(_translate("MainWindow", "Column only"))
        self.chkBx_columnSec.setText(_translate("MainWindow", "Column"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuGraphics.setTitle(_translate("MainWindow", "Graphics"))
        self.outputDock.setWindowTitle(_translate("MainWindow", "Output dock"))
        self.label_157.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Compression Member</span></p></body></html>"))
        self.btn_SaveMessages.setToolTip(_translate("MainWindow", "Save log messages"))
        self.btn_SaveMessages.setText(_translate("MainWindow", "Save messages"))
        self.btn_CreateDesign.setToolTip(_translate("MainWindow", "Create design report"))
        self.btn_CreateDesign.setText(_translate("MainWindow", "Create design report"))
        self.label_156.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Compression capacity in </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Major axis (z-z) (kN)</p></body></html>"))
        self.label_159.setText(_translate("MainWindow", "<html><head/><body><p>Compression capacity in </p><p>Minor axis (y-y) (kN)</p></body></html>"))
        self.label_170.setText(_translate("MainWindow", "Utility ratio (z-z)"))
        self.label_171.setText(_translate("MainWindow", "Slenderness value (z-z)"))
        self.label_172.setText(_translate("MainWindow", "Slenderness value (y-y)"))
        self.label_173.setText(_translate("MainWindow", "Utility ratio (y-y)"))
        self.inputDock.setWindowTitle(_translate("MainWindow", "Input dock"))
        self.txt_Fy.setPlaceholderText(_translate("MainWindow", "000"))
        self.txt_Fu.setPlaceholderText(_translate("MainWindow", "000"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Compression member</p></body></html>"))
        self.lbl_fu.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">f</span><span style=\" font-style:italic; vertical-align:sub;\">u </span>(MPa) * </p></body></html>"))
        self.lbl_fy.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">f</span><span style=\" vertical-align:sub;\">y </span>(MPa) *</p></body></html>"))
        self.btn_Reset.setToolTip(_translate("MainWindow", "Alt+R"))
        self.btn_Reset.setText(_translate("MainWindow", "Reset"))
        self.btn_Reset.setShortcut(_translate("MainWindow", "Alt+R"))
        self.btn_Design.setToolTip(_translate("MainWindow", "Alt+D"))
        self.btn_Design.setText(_translate("MainWindow", "Design"))
        self.btn_Design.setShortcut(_translate("MainWindow", "Alt+D"))
        self.lbl_column.setText(_translate("MainWindow", "<html><head/><body><p>Section Type*</p></body></html>"))
        self.combo_sectiontype.setItemText(0, _translate("MainWindow", "Select Type"))
        self.combo_sectiontype.setItemText(1, _translate("MainWindow", "Beams"))
        self.combo_sectiontype.setItemText(2, _translate("MainWindow", "Columns"))
        self.combo_sectiontype.setItemText(3, _translate("MainWindow", "Angles"))
        self.combo_sectiontype.setItemText(4, _translate("MainWindow", "Back to Back Angles"))
        self.combo_sectiontype.setItemText(5, _translate("MainWindow", "Star Angles"))
        self.combo_sectiontype.setItemText(6, _translate("MainWindow", "Channels"))
        self.combo_sectiontype.setItemText(7, _translate("MainWindow", "Back to Back Channels"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Factored loads</span></p></body></html>"))
        self.lbl_axial.setText(_translate("MainWindow", "Axial Force (kN) *"))
        self.lbl_beam1_10.setText(_translate("MainWindow", "<html><head/><body><p>Length (z-z)</p></body></html>"))
        self.combo_end1_cond1.setItemText(0, _translate("MainWindow", "Translation"))
        self.combo_end1_cond1.setItemText(1, _translate("MainWindow", "Free"))
        self.combo_end1_cond1.setItemText(2, _translate("MainWindow", "Restrained"))
        self.combo_end2_cond1.setItemText(0, _translate("MainWindow", "Translation"))
        self.combo_end2_cond1.setItemText(1, _translate("MainWindow", "Free"))
        self.combo_end2_cond1.setItemText(2, _translate("MainWindow", "Restrained"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>End 1</p></body></html>"))
        self.combo_end2_cond2.setItemText(0, _translate("MainWindow", "Rotation"))
        self.combo_end2_cond2.setItemText(1, _translate("MainWindow", "Free"))
        self.combo_end2_cond2.setItemText(2, _translate("MainWindow", "Restrained"))
        self.combo_end1_cond2.setItemText(0, _translate("MainWindow", "Rotation"))
        self.combo_end1_cond2.setItemText(1, _translate("MainWindow", "Free"))
        self.combo_end1_cond2.setItemText(2, _translate("MainWindow", "Restrained"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>End 2</p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p>Support Condition</p></body></html>"))
        self.lbl_column_2.setText(_translate("MainWindow", "<html><head/><body><p>Section Size *</p></body></html>"))
        self.Plate_thk.setText(_translate("MainWindow", "<html><head/><body><p>Plate thk (mm)</p></body></html>"))
        self.lbl_beam1_11.setText(_translate("MainWindow", "<html><head/><body><p>Length (y-y)</p></body></html>"))
        self.actionInput.setText(_translate("MainWindow", "Input"))
        self.actionInput.setToolTip(_translate("MainWindow", "Input browser"))
        self.actionInputwindow.setText(_translate("MainWindow", "inputwindow"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_load_input.setText(_translate("MainWindow", "Load input"))
        self.action_load_input.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action_save_input.setText(_translate("MainWindow", "Save input"))
        self.action_save_input.setIconText(_translate("MainWindow", "Save input"))
        self.action_save_input.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionInput_Browser.setText(_translate("MainWindow", "Input Browser"))
        self.actionOutput_Browser.setText(_translate("MainWindow", "Output Browser"))
        self.actionAbout_Osdag.setText(_translate("MainWindow", "About Osdag"))
        self.actionBeam.setText(_translate("MainWindow", "Beam"))
        self.actionColumn.setText(_translate("MainWindow", "Column"))
        self.actionFinplate.setText(_translate("MainWindow", "Finplate"))
        self.actionBolt.setText(_translate("MainWindow", "Bolt"))
        self.action2D_view.setText(_translate("MainWindow", "2D view"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.actionPan.setText(_translate("MainWindow", "Pan"))
        self.actionRotate_3D_model.setText(_translate("MainWindow", "Rotate 3D model"))
        self.actionView_2D_on_XY.setText(_translate("MainWindow", "View 2D on XY"))
        self.actionView_2D_on_YZ.setText(_translate("MainWindow", "View 2D on YZ"))
        self.actionView_2D_on_ZX.setText(_translate("MainWindow", "View 2D on ZX"))
        self.actionModel.setText(_translate("MainWindow", "Model"))
        self.actionEnlarge_font_size.setText(_translate("MainWindow", "Font"))
        self.actionReduce_font_size.setText(_translate("MainWindow", "Reduce font size"))
        self.actionSave_3D_model.setText(_translate("MainWindow", "Save 3D model "))
        self.actionSave_3D_model.setShortcut(_translate("MainWindow", "Alt+3"))
        self.actionSave_current_image.setText(_translate("MainWindow", "Save CAD image "))
        self.actionSave_current_image.setShortcut(_translate("MainWindow", "Alt+I"))
        self.actionSave_log_messages.setText(_translate("MainWindow", "Save log messages"))
        self.actionSave_log_messages.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionCreate_design_report.setText(_translate("MainWindow", "Create design report"))
        self.actionCreate_design_report.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionQuit_fin_plate_design.setText(_translate("MainWindow", "Quit fin plate design"))
        self.actionSave_Front_View.setText(_translate("MainWindow", "Save front view"))
        self.actionSave_Front_View.setShortcut(_translate("MainWindow", "Alt+Shift+F"))
        self.actionSave_Top_View.setText(_translate("MainWindow", "Save top view"))
        self.actionSave_Top_View.setShortcut(_translate("MainWindow", "Alt+Shift+T"))
        self.actionSave_Side_View.setText(_translate("MainWindow", "Save side view"))
        self.actionSave_Side_View.setShortcut(_translate("MainWindow", "Alt+Shift+S"))
        self.actionChange_bg_color.setText(_translate("MainWindow", "Change bg color"))
        self.actionShow_beam.setText(_translate("MainWindow", "Show beam"))
        self.actionShow_beam.setShortcut(_translate("MainWindow", "Alt+Shift+B"))
        self.actionShow_column.setText(_translate("MainWindow", "Show column"))
        self.actionShow_column.setShortcut(_translate("MainWindow", "Alt+Shift+C"))
        self.actionShow_connector.setText(_translate("MainWindow", "Show connector"))
        self.actionShow_connector.setShortcut(_translate("MainWindow", "Alt+Shift+A"))
        self.actionChange_background.setText(_translate("MainWindow", "Change background"))
        self.actionShow_all.setText(_translate("MainWindow", "Show all"))
        self.actionShow_all.setShortcut(_translate("MainWindow", "Alt+Shift+M"))
        self.actionDesign_examples.setText(_translate("MainWindow", "Design Examples"))
        self.actionSample_Problems.setText(_translate("MainWindow", "Sample Problems"))
        self.actionSample_Tutorials.setText(_translate("MainWindow", "Video Tutorials"))
        self.actionAbout_Osdag_2.setText(_translate("MainWindow", "About Osdag"))
        self.actionOsdag_Manual.setText(_translate("MainWindow", "Osdag Manual"))
        self.actionAsk_Us_a_Question.setText(_translate("MainWindow", "Ask Us a Question"))
        self.actionFAQ.setText(_translate("MainWindow", "FAQ"))
        self.actionDesign_Preferences.setText(_translate("MainWindow", "Design Preferences"))
        self.actionDesign_Preferences.setShortcut(_translate("MainWindow", "Alt+P"))
        self.actionfinPlate_quit.setText(_translate("MainWindow", "Quit"))
        self.actionfinPlate_quit.setShortcut(_translate("MainWindow", "Shift+Q"))
        self.actio_load_input.setText(_translate("MainWindow", "Load input"))
        self.actio_load_input.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionShow_column_2.setText(_translate("MainWindow", "Show column"))
        self.actionShow_column_2.setShortcut(_translate("MainWindow", "Alt+Shift+C"))
    def comboChanged(self):
        lst=["Back to Back Angles","Star Angles","Back to Back Channels"]
        comboText=self.combo_sectiontype.currentText()
        if comboText in lst:
            self.txt_plate_thk.setEnabled(True)
        else:
            self.txt_plate_thk.setEnabled(False)


from . import icons_rc
