# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_flangespliceplate_inner.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlangespliceplateInner(object):
    def setupUi(self, FlangespliceplateInner):
        FlangespliceplateInner.setObjectName("FlangespliceplateInner")
        FlangespliceplateInner.resize(289, 274)
        self.formLayout = QtWidgets.QFormLayout(FlangespliceplateInner)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.plateHeight = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plateHeight.setFont(font)
        self.plateHeight.setObjectName("plateHeight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.plateHeight)
        self.txt_outer_plateHeight = QtWidgets.QLineEdit(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_outer_plateHeight.setFont(font)
        self.txt_outer_plateHeight.setReadOnly(True)
        self.txt_outer_plateHeight.setObjectName("txt_outer_plateHeight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_outer_plateHeight)
        self.label_2 = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_outer_plateWidth = QtWidgets.QLineEdit(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_outer_plateWidth.setFont(font)
        self.txt_outer_plateWidth.setReadOnly(True)
        self.txt_outer_plateWidth.setObjectName("txt_outer_plateWidth")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_outer_plateWidth)
        self.label_3 = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txt_inner_plateHeight = QtWidgets.QLineEdit(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_inner_plateHeight.setFont(font)
        self.txt_inner_plateHeight.setObjectName("txt_inner_plateHeight")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_inner_plateHeight)
        self.label_5 = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txt_inner_plateWidth = QtWidgets.QLineEdit(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_inner_plateWidth.setFont(font)
        self.txt_inner_plateWidth.setObjectName("txt_inner_plateWidth")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_inner_plateWidth)
        self.label_162 = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_162.setFont(font)
        self.label_162.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_162.setObjectName("label_162")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_162)
        self.label_163 = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_163.setFont(font)
        self.label_163.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_163.setObjectName("label_163")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_163)
        self.txt_plateDemand = QtWidgets.QLineEdit(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateDemand.setFont(font)
        self.txt_plateDemand.setReadOnly(True)
        self.txt_plateDemand.setObjectName("txt_plateDemand")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txt_plateDemand)
        self.label_164 = QtWidgets.QLabel(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_164.setFont(font)
        self.label_164.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_164.setObjectName("label_164")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_164)
        self.txt_plateCapacity = QtWidgets.QLineEdit(FlangespliceplateInner)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateCapacity.setFont(font)
        self.txt_plateCapacity.setReadOnly(True)
        self.txt_plateCapacity.setObjectName("txt_plateCapacity")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.txt_plateCapacity)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem1)

        self.retranslateUi(FlangespliceplateInner)
        QtCore.QMetaObject.connectSlotsByName(FlangespliceplateInner)

    def retranslateUi(self, FlangespliceplateInner):
        _translate = QtCore.QCoreApplication.translate
        FlangespliceplateInner.setWindowTitle(_translate("FlangespliceplateInner", "Flange splice plate"))
        self.label.setText(_translate("FlangespliceplateInner", "Outer flange splice plate"))
        self.plateHeight.setText(_translate("FlangespliceplateInner", "Height (mm)"))
        self.label_2.setText(_translate("FlangespliceplateInner", "Width (mm)"))
        self.label_3.setText(_translate("FlangespliceplateInner", "Inner flange splice plate"))
        self.label_4.setText(_translate("FlangespliceplateInner", "Height (mm)"))
        self.label_5.setText(_translate("FlangespliceplateInner", "Width (mm)"))
        self.label_162.setText(_translate("FlangespliceplateInner", "<html><head/><body><p>Strength</p></body></html>"))
        self.label_163.setText(_translate("FlangespliceplateInner", "<html><head/><body><p>Demand (kN)</p></body></html>"))
        self.label_164.setText(_translate("FlangespliceplateInner", "<html><head/><body><p>Capacity (kN)</p></body></html>"))
