# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_flangespliceplate.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_flangespliceplate(object):
    def setupUi(self, flangespliceplate):
        flangespliceplate.setObjectName("flangespliceplate")
        flangespliceplate.resize(377, 166)
        self.formLayout = QtWidgets.QFormLayout(flangespliceplate)
        self.formLayout.setObjectName("formLayout")
        self.plateHeight = QtWidgets.QLabel(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plateHeight.setFont(font)
        self.plateHeight.setObjectName("plateHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.plateHeight)
        self.txt_plateHeight = QtWidgets.QLineEdit(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateHeight.setFont(font)
        self.txt_plateHeight.setReadOnly(True)
        self.txt_plateHeight.setObjectName("txt_plateHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_plateHeight)
        self.label_2 = QtWidgets.QLabel(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_plateWidth = QtWidgets.QLineEdit(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateWidth.setFont(font)
        self.txt_plateWidth.setReadOnly(True)
        self.txt_plateWidth.setObjectName("txt_plateWidth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_plateWidth)
        self.label_162 = QtWidgets.QLabel(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_162.setFont(font)
        self.label_162.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_162.setObjectName("label_162")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_162)
        self.label_163 = QtWidgets.QLabel(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_163.setFont(font)
        self.label_163.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_163.setObjectName("label_163")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_163)
        self.txt_plateDemand = QtWidgets.QLineEdit(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateDemand.setFont(font)
        self.txt_plateDemand.setReadOnly(True)
        self.txt_plateDemand.setObjectName("txt_plateDemand")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_plateDemand)
        self.label_164 = QtWidgets.QLabel(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_164.setFont(font)
        self.label_164.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_164.setObjectName("label_164")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_164)
        self.txt_plateCapacity = QtWidgets.QLineEdit(flangespliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateCapacity.setFont(font)
        self.txt_plateCapacity.setReadOnly(True)
        self.txt_plateCapacity.setObjectName("txt_plateCapacity")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_plateCapacity)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)

        self.retranslateUi(flangespliceplate)
        QtCore.QMetaObject.connectSlotsByName(flangespliceplate)

    def retranslateUi(self, flangespliceplate):
        _translate = QtCore.QCoreApplication.translate
        flangespliceplate.setWindowTitle(_translate("flangespliceplate", "Flange splice plate"))
        self.plateHeight.setText(_translate("flangespliceplate", "Height (mm)"))
        self.label_2.setText(_translate("flangespliceplate", "Width (mm)"))
        self.label_162.setText(_translate("flangespliceplate", "<html><head/><body><p>Strength</p></body></html>"))
        self.label_163.setText(_translate("flangespliceplate", "<html><head/><body><p>Demand (kN)</p></body></html>"))
        self.label_164.setText(_translate("flangespliceplate", "<html><head/><body><p>Capacity (kN)</p></body></html>"))
