# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_webspliceplate.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_webspliceplate(object):
    def setupUi(self, webspliceplate):
        webspliceplate.setObjectName("webspliceplate")
        webspliceplate.resize(279, 177)
        self.formLayout = QtWidgets.QFormLayout(webspliceplate)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.plateHeight_2 = QtWidgets.QLabel(webspliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plateHeight_2.setFont(font)
        self.plateHeight_2.setObjectName("plateHeight_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.plateHeight_2)
        self.txt_plateHeight = QtWidgets.QLineEdit(webspliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateHeight.setFont(font)
        self.txt_plateHeight.setReadOnly(True)
        self.txt_plateHeight.setObjectName("txt_plateHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_plateHeight)
        self.label_3 = QtWidgets.QLabel(webspliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txt_plateWidth = QtWidgets.QLineEdit(webspliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateWidth.setFont(font)
        self.txt_plateWidth.setReadOnly(True)
        self.txt_plateWidth.setObjectName("txt_plateWidth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_plateWidth)
        self.label = QtWidgets.QLabel(webspliceplate)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_163 = QtWidgets.QLabel(webspliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_163.setFont(font)
        self.label_163.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_163.setObjectName("label_163")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_163)
        self.txt_plateDemand = QtWidgets.QLineEdit(webspliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txt_plateDemand.setFont(font)
        self.txt_plateDemand.setReadOnly(True)
        self.txt_plateDemand.setObjectName("txt_plateDemand")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_plateDemand)
        self.label_2 = QtWidgets.QLabel(webspliceplate)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_plateCapacity = QtWidgets.QLineEdit(webspliceplate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_plateCapacity.setFont(font)
        self.txt_plateCapacity.setObjectName("txt_plateCapacity")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_plateCapacity)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem1)

        self.retranslateUi(webspliceplate)
        QtCore.QMetaObject.connectSlotsByName(webspliceplate)

    def retranslateUi(self, webspliceplate):
        _translate = QtCore.QCoreApplication.translate
        webspliceplate.setWindowTitle(_translate("webspliceplate", "Web splice plate"))
        self.plateHeight_2.setText(_translate("webspliceplate", "Height (mm)"))
        self.label_3.setText(_translate("webspliceplate", "Width (mm)"))
        self.label.setText(_translate("webspliceplate", "Strength"))
        self.label_163.setText(_translate("webspliceplate", "<html><head/><body><p>Demand (kN)</p></body></html>"))
        self.label_2.setText(_translate("webspliceplate", "Capacity (kN)"))
